package top.codesky.forcoder.model.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   问题表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table question
 */
public class Question {
    /**
     * Database Column Remarks:
     *   自增主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   问题标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.title
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    private String title;

    /**
     * Database Column Remarks:
     *   问题的回答数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answer_count
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    private int answerCount;

    /**
     * Database Column Remarks:
     *   问题的评论数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.comment_count
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    private int commentCount;

    /**
     * Database Column Remarks:
     *   问题的关注人数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.follower_count
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    private int followerCount;

    /**
     * Database Column Remarks:
     *   提问者的id，匿名id为0
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.author_id
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    private Long authorId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.gmt_create
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   上一次的更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.gmt_modified
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    private Date gmtModified;

    /**
     * Database Column Remarks:
     *   问题内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.content
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public Question(Long id, String title, int answerCount, int commentCount, int followerCount, Long authorId, Date gmtCreate, Date gmtModified) {
        this.id = id;
        this.title = title;
        this.answerCount = answerCount;
        this.commentCount = commentCount;
        this.followerCount = followerCount;
        this.authorId = authorId;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
    }
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public Question(Long id, String title, int answerCount, int commentCount, int followerCount, Long authorId, Date gmtCreate, Date gmtModified, String content) {
        this.id = id;
        this.title = title;
        this.answerCount = answerCount;
        this.commentCount = commentCount;
        this.followerCount = followerCount;
        this.authorId = authorId;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public Question() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.title
     *
     * @return the value of question.title
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.title
     *
     * @param title the value for question.title
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answer_count
     *
     * @return the value of question.answer_count
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public int getAnswerCount() {
        return answerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answer_count
     *
     * @param answerCount the value for question.answer_count
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public void setAnswerCount(int answerCount) {
        this.answerCount = answerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.comment_count
     *
     * @return the value of question.comment_count
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public int getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.comment_count
     *
     * @param commentCount the value for question.comment_count
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public void setCommentCount(int commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.follower_count
     *
     * @return the value of question.follower_count
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public int getFollowerCount() {
        return followerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.follower_count
     *
     * @param followerCount the value for question.follower_count
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public void setFollowerCount(int followerCount) {
        this.followerCount = followerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.author_id
     *
     * @return the value of question.author_id
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public Long getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.author_id
     *
     * @param authorId the value for question.author_id
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.gmt_create
     *
     * @return the value of question.gmt_create
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.gmt_create
     *
     * @param gmtCreate the value for question.gmt_create
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.gmt_modified
     *
     * @return the value of question.gmt_modified
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.gmt_modified
     *
     * @param gmtModified the value for question.gmt_modified
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.content
     *
     * @return the value of question.content
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.content
     *
     * @param content the value for question.content
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}