package top.codesky.forcoder.model.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table question
 */
public class Question {
    /**
     * Database Column Remarks:
     *   自增主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   问题标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.title
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    private String title;

    /**
     * Database Column Remarks:
     *   问题的回答数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answer_count
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    private int answerCount;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.gmt_create
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   上一次的更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.gmt_modified
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    private Date gmtModified;

    /**
     * Database Column Remarks:
     *   提问者的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.author_id
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    private Long authorId;

    /**
     * Database Column Remarks:
     *   问题内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.content
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    public Question(Long id, String title, int answerCount, Date gmtCreate, Date gmtModified, Long authorId) {
        this.id = id;
        this.title = title;
        this.answerCount = answerCount;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    public Question(Long id, String title, int answerCount, Date gmtCreate, Date gmtModified, Long authorId, String content) {
        this.id = id;
        this.title = title;
        this.answerCount = answerCount;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
        this.authorId = authorId;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    public Question() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.title
     *
     * @return the value of question.title
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.title
     *
     * @param title the value for question.title
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answer_count
     *
     * @return the value of question.answer_count
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    public int getAnswerCount() {
        return answerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answer_count
     *
     * @param answerCount the value for question.answer_count
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    public void setAnswerCount(int answerCount) {
        this.answerCount = answerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.gmt_create
     *
     * @return the value of question.gmt_create
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.gmt_create
     *
     * @param gmtCreate the value for question.gmt_create
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.gmt_modified
     *
     * @return the value of question.gmt_modified
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.gmt_modified
     *
     * @param gmtModified the value for question.gmt_modified
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.author_id
     *
     * @return the value of question.author_id
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    public Long getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.author_id
     *
     * @param authorId the value for question.author_id
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.content
     *
     * @return the value of question.content
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.content
     *
     * @param content the value for question.content
     *
     * @mbg.generated 2019-04-24 18:03:44
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}