package top.codesky.forcoder.model.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   用户登录认证相关信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_authentication_info
 */
public class UserAuthenticationInfo {
    /**
     * Database Column Remarks:
     *   自增id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_authentication_info.id
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_authentication_info.username
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    private String username;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_authentication_info.password
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    private String password;

    /**
     * Database Column Remarks:
     *   账户未过期标志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_authentication_info.is_account_non_expired
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    private boolean accountNonExpired;

    /**
     * Database Column Remarks:
     *   账户未锁定标志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_authentication_info.is_account_non_locked
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    private boolean accountNonLocked;

    /**
     * Database Column Remarks:
     *   密码未过期标志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_authentication_info.is_credentials_non_expired
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    private boolean credentialsNonExpired;

    /**
     * Database Column Remarks:
     *   账户可用标志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_authentication_info.is_enabled
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    private boolean enabled;

    /**
     * Database Column Remarks:
     *   账户创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_authentication_info.gmt_create
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   账户的最近一次修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_authentication_info.gmt_modified
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authentication_info
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public UserAuthenticationInfo(Long id, String username, String password, boolean accountNonExpired, boolean accountNonLocked, boolean credentialsNonExpired, boolean enabled, Date gmtCreate, Date gmtModified) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.accountNonExpired = accountNonExpired;
        this.accountNonLocked = accountNonLocked;
        this.credentialsNonExpired = credentialsNonExpired;
        this.enabled = enabled;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authentication_info
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public UserAuthenticationInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authentication_info.id
     *
     * @return the value of user_authentication_info.id
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authentication_info.id
     *
     * @param id the value for user_authentication_info.id
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authentication_info.username
     *
     * @return the value of user_authentication_info.username
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authentication_info.username
     *
     * @param username the value for user_authentication_info.username
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authentication_info.password
     *
     * @return the value of user_authentication_info.password
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authentication_info.password
     *
     * @param password the value for user_authentication_info.password
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authentication_info.is_account_non_expired
     *
     * @return the value of user_authentication_info.is_account_non_expired
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public boolean isAccountNonExpired() {
        return accountNonExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authentication_info.is_account_non_expired
     *
     * @param accountNonExpired the value for user_authentication_info.is_account_non_expired
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public void setAccountNonExpired(boolean accountNonExpired) {
        this.accountNonExpired = accountNonExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authentication_info.is_account_non_locked
     *
     * @return the value of user_authentication_info.is_account_non_locked
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public boolean isAccountNonLocked() {
        return accountNonLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authentication_info.is_account_non_locked
     *
     * @param accountNonLocked the value for user_authentication_info.is_account_non_locked
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public void setAccountNonLocked(boolean accountNonLocked) {
        this.accountNonLocked = accountNonLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authentication_info.is_credentials_non_expired
     *
     * @return the value of user_authentication_info.is_credentials_non_expired
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public boolean isCredentialsNonExpired() {
        return credentialsNonExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authentication_info.is_credentials_non_expired
     *
     * @param credentialsNonExpired the value for user_authentication_info.is_credentials_non_expired
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public void setCredentialsNonExpired(boolean credentialsNonExpired) {
        this.credentialsNonExpired = credentialsNonExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authentication_info.is_enabled
     *
     * @return the value of user_authentication_info.is_enabled
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authentication_info.is_enabled
     *
     * @param enabled the value for user_authentication_info.is_enabled
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authentication_info.gmt_create
     *
     * @return the value of user_authentication_info.gmt_create
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authentication_info.gmt_create
     *
     * @param gmtCreate the value for user_authentication_info.gmt_create
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_authentication_info.gmt_modified
     *
     * @return the value of user_authentication_info.gmt_modified
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_authentication_info.gmt_modified
     *
     * @param gmtModified the value for user_authentication_info.gmt_modified
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}