package top.codesky.forcoder.model.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 * 用户个人描述信息表
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_addition_info
 */
public class UserAdditionInfo {
    /**
     * Database Column Remarks:
     * 自增id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addition_info.id
     *
     * @mbg.generated 2019-05-05 17:11:10
     */
    private Long id;

    /**
     * Database Column Remarks:
     * 用户名
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addition_info.username
     *
     * @mbg.generated 2019-05-05 17:11:10
     */
    private String username;

    /**
     * Database Column Remarks:
     * 关联用户认证表外键
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addition_info.user_id
     *
     * @mbg.generated 2019-05-05 17:11:10
     */
    private Long userId;

    /**
     * Database Column Remarks:
     * 性别
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addition_info.gender
     *
     * @mbg.generated 2019-05-05 17:11:10
     */
    private short gender;

    /**
     * Database Column Remarks:
     * 用户头像url
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addition_info.avatar_url
     *
     * @mbg.generated 2019-05-05 17:11:10
     */
    private String avatarUrl;

    /**
     * Database Column Remarks:
     * 一句话介绍
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addition_info.headline
     *
     * @mbg.generated 2019-05-05 17:11:10
     */
    private String headline;

    /**
     * Database Column Remarks:
     * 所在行业
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addition_info.business
     *
     * @mbg.generated 2019-05-05 17:11:10
     */
    private String business;

    /**
     * Database Column Remarks:
     * 创建时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addition_info.gmt_created
     *
     * @mbg.generated 2019-05-05 17:11:10
     */
    private Date gmtCreated;

    /**
     * Database Column Remarks:
     * 修改时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addition_info.gmt_modified
     *
     * @mbg.generated 2019-05-05 17:11:10
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addition_info
     *
     * @mbg.generated 2019-05-05 17:11:10
     */
    public UserAdditionInfo(Long id, String username, Long userId, short gender, String avatarUrl, String headline, String business, Date gmtCreated, Date gmtModified) {
        this.id = id;
        this.username = username;
        this.userId = userId;
        this.gender = gender;
        this.avatarUrl = avatarUrl;
        this.headline = headline;
        this.business = business;
        this.gmtCreated = gmtCreated;
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_addition_info
     *
     * @mbg.generated 2019-05-05 17:11:10
     */
    public UserAdditionInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addition_info.id
     *
     * @return the value of user_addition_info.id
     * @mbg.generated 2019-05-05 17:11:10
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addition_info.id
     *
     * @param id the value for user_addition_info.id
     * @mbg.generated 2019-05-05 17:11:10
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addition_info.username
     *
     * @return the value of user_addition_info.username
     * @mbg.generated 2019-05-05 17:11:10
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addition_info.username
     *
     * @param username the value for user_addition_info.username
     * @mbg.generated 2019-05-05 17:11:10
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addition_info.user_id
     *
     * @return the value of user_addition_info.user_id
     * @mbg.generated 2019-05-05 17:11:10
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addition_info.user_id
     *
     * @param userId the value for user_addition_info.user_id
     * @mbg.generated 2019-05-05 17:11:10
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addition_info.gender
     *
     * @return the value of user_addition_info.gender
     * @mbg.generated 2019-05-05 17:11:10
     */
    public short getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addition_info.gender
     *
     * @param gender the value for user_addition_info.gender
     * @mbg.generated 2019-05-05 17:11:10
     */
    public void setGender(short gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addition_info.avatar_url
     *
     * @return the value of user_addition_info.avatar_url
     * @mbg.generated 2019-05-05 17:11:10
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addition_info.avatar_url
     *
     * @param avatarUrl the value for user_addition_info.avatar_url
     * @mbg.generated 2019-05-05 17:11:10
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addition_info.headline
     *
     * @return the value of user_addition_info.headline
     * @mbg.generated 2019-05-05 17:11:10
     */
    public String getHeadline() {
        return headline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addition_info.headline
     *
     * @param headline the value for user_addition_info.headline
     * @mbg.generated 2019-05-05 17:11:10
     */
    public void setHeadline(String headline) {
        this.headline = headline == null ? null : headline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addition_info.business
     *
     * @return the value of user_addition_info.business
     * @mbg.generated 2019-05-05 17:11:10
     */
    public String getBusiness() {
        return business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addition_info.business
     *
     * @param business the value for user_addition_info.business
     * @mbg.generated 2019-05-05 17:11:10
     */
    public void setBusiness(String business) {
        this.business = business == null ? null : business.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addition_info.gmt_created
     *
     * @return the value of user_addition_info.gmt_created
     * @mbg.generated 2019-05-05 17:11:10
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addition_info.gmt_created
     *
     * @param gmtCreated the value for user_addition_info.gmt_created
     * @mbg.generated 2019-05-05 17:11:10
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addition_info.gmt_modified
     *
     * @return the value of user_addition_info.gmt_modified
     * @mbg.generated 2019-05-05 17:11:10
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addition_info.gmt_modified
     *
     * @param gmtModified the value for user_addition_info.gmt_modified
     * @mbg.generated 2019-05-05 17:11:10
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public static UserAdditionInfo copyOf(UserAdditionInfo userAdditionInfo) {
        UserAdditionInfo newInstance = new UserAdditionInfo();

        newInstance.id = userAdditionInfo.id;
        newInstance.username = userAdditionInfo.username;
        newInstance.userId = userAdditionInfo.userId;
        newInstance.gender = userAdditionInfo.gender;
        newInstance.avatarUrl = userAdditionInfo.avatarUrl;
        newInstance.headline = userAdditionInfo.headline;
        newInstance.business = userAdditionInfo.business;
        newInstance.gmtCreated = userAdditionInfo.gmtCreated;
        newInstance.gmtModified = userAdditionInfo.gmtModified;

        return newInstance;
    }
}