package top.codesky.forcoder.model.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 */
public class User {
    /**
     * Database Column Remarks:
     *   自增id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    private String username;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    private String password;

    /**
     * Database Column Remarks:
     *   性别：1 男 ，0 女
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    private short gender;

    /**
     * Database Column Remarks:
     *   用户头像url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar_url
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    private String avatarUrl;

    /**
     * Database Column Remarks:
     *   账户未过期标志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_account_non_expired
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    private boolean accountNonExpired;

    /**
     * Database Column Remarks:
     *   账户未锁定标志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_account_non_locked
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    private boolean accountNonLocked;

    /**
     * Database Column Remarks:
     *   密码未过期标志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_credentials_non_expired
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    private boolean credentialsNonExpired;

    /**
     * Database Column Remarks:
     *   账户可用标志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_enabled
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    private boolean enabled;

    /**
     * Database Column Remarks:
     *   账户创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gmt_create
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   账户的最近一次修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gmt_modified
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public User(Long id, String username, String password, short gender, String avatarUrl, boolean accountNonExpired, boolean accountNonLocked, boolean credentialsNonExpired, boolean enabled, Date gmtCreate, Date gmtModified) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.gender = gender;
        this.avatarUrl = avatarUrl;
        this.accountNonExpired = accountNonExpired;
        this.accountNonLocked = accountNonLocked;
        this.credentialsNonExpired = credentialsNonExpired;
        this.enabled = enabled;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public short getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public void setGender(short gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar_url
     *
     * @return the value of user.avatar_url
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar_url
     *
     * @param avatarUrl the value for user.avatar_url
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_account_non_expired
     *
     * @return the value of user.is_account_non_expired
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public boolean isAccountNonExpired() {
        return accountNonExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_account_non_expired
     *
     * @param accountNonExpired the value for user.is_account_non_expired
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public void setAccountNonExpired(boolean accountNonExpired) {
        this.accountNonExpired = accountNonExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_account_non_locked
     *
     * @return the value of user.is_account_non_locked
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public boolean isAccountNonLocked() {
        return accountNonLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_account_non_locked
     *
     * @param accountNonLocked the value for user.is_account_non_locked
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public void setAccountNonLocked(boolean accountNonLocked) {
        this.accountNonLocked = accountNonLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_credentials_non_expired
     *
     * @return the value of user.is_credentials_non_expired
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public boolean isCredentialsNonExpired() {
        return credentialsNonExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_credentials_non_expired
     *
     * @param credentialsNonExpired the value for user.is_credentials_non_expired
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public void setCredentialsNonExpired(boolean credentialsNonExpired) {
        this.credentialsNonExpired = credentialsNonExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_enabled
     *
     * @return the value of user.is_enabled
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_enabled
     *
     * @param enabled the value for user.is_enabled
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gmt_create
     *
     * @return the value of user.gmt_create
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gmt_create
     *
     * @param gmtCreate the value for user.gmt_create
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gmt_modified
     *
     * @return the value of user.gmt_modified
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gmt_modified
     *
     * @param gmtModified the value for user.gmt_modified
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}