package top.codesky.forcoder.dao;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;
import top.codesky.forcoder.model.entity.Answer;
import top.codesky.forcoder.model.params.AnswerCountQuery;
import top.codesky.forcoder.model.vo.AnswerDetailsVO;

import java.util.List;

@Mapper
@Repository
public interface AnswerMapper {

    /**
     * 通过answer id统计数量，判断答案是否存在
     *
     * @param answerId answer id
     * @return the num of answer : 0 or 1
     */
    int countAnswerByAnswerId(long answerId);


    AnswerDetailsVO selectAnswerByAnswerId(long answerId);

    /**
     * 通过user id 和 question id，判断用户是否已经作答
     *
     * @param answerCountQuery contain questionId and userId
     * @return count result
     */
    int countUserAnswerByQuestionId(AnswerCountQuery answerCountQuery);


    /**
     * 查询最新的一条回答作为首页问答返回记录
     *
     * @param questionId 问题id
     * @return
     */
    AnswerDetailsVO selectAnswerByQuestionId(Long questionId);

    /**
     * 获取问题的相关回答 默认10条
     *
     * @param questionId
     * @return
     */
    List<AnswerDetailsVO> selectAnswersByQuestionId(Long questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int insert(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int insertSelective(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    Answer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int updateByPrimaryKeySelective(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int updateByPrimaryKeyWithBLOBs(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int updateByPrimaryKey(Answer record);
}