package top.codesky.forcoder.dao;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;
import top.codesky.forcoder.model.entity.Answer;
import top.codesky.forcoder.model.vo.AnswerDetailsVo;

import java.util.List;

@Mapper
@Repository
public interface AnswerMapper {

    /**
     * 获取问题的相关回答 默认10条
     *
     * @param questionId
     * @return
     */
    List<AnswerDetailsVo> selectAnswersByQuestionId(Long questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int insert(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int insertSelective(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    Answer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int updateByPrimaryKeySelective(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int updateByPrimaryKeyWithBLOBs(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int updateByPrimaryKey(Answer record);
}