package top.codesky.forcoder.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import top.codesky.forcoder.model.entity.Question;
import top.codesky.forcoder.model.vo.QuestionWithAuthor;
import top.codesky.forcoder.model.params.QuestionDeleteParam;
import top.codesky.forcoder.model.vo.QuestionDetailsVO;

import java.util.List;

@Repository
@Mapper
public interface QuestionMapper {


    /**
     * count question number by question id
     *
     * @param questionId quesion id
     * @return num of question (0 or 1)
     */
    int countQuestionByQuestionId(long questionId);

    /**
     * 根据问题id，查询问题的相关信息，包括 问题+作者信息
     *
     * @param questionId
     * @return
     */
    QuestionDetailsVO selectQuestionDetailsByQuestionId(Long questionId);

    /**
     * 分页查询最新的问题list
     *
     * @param offset
     * @param limit
     * @return
     */
    List<QuestionWithAuthor> selectLatestQuestionByPage(@Param("offset") long offset, @Param("limit") long limit);


    /**
     * 根据问题id和用户id，删除问题
     *
     * @param params
     * @return
     */
    int deleteByQuestionIdAndUserId(QuestionDeleteParam params);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int insert(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int insertSelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    Question selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int updateByPrimaryKeySelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int updateByPrimaryKeyWithBLOBs(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int updateByPrimaryKey(Question record);
}