package top.codesky.forcoder.dao;

import org.apache.ibatis.annotations.Mapper;
import top.codesky.forcoder.model.entity.User;
import top.codesky.forcoder.model.entity.UserForAuthentication;

@Mapper
public interface UserMapper {

    /**
     * 根据用户名，查找用户授权信息
     *
     * @param username 用户名:唯一
     * @return
     */
    UserForAuthentication findByUsername(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    User selectByPrimaryKey(Long id);

    User selectByUsername(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated 2019-04-22 20:06:12
     */
    int updateByPrimaryKey(User record);
}