package top.codesky.forcoder.dao;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;
import top.codesky.forcoder.model.entity.UserAuthenticationInfo;
import top.codesky.forcoder.model.entity.UserForAuthentication;

@Repository
@Mapper
public interface UserAuthenticationInfoMapper {

    /**
     * 根据用户名，查询用户的认证信息
     *
     * @param username
     * @return
     */
    UserForAuthentication selectAuthenticationInfoByUsername(String username);

    /**
     * 查询用户是否已存在
     *
     * @param username
     * @return
     */
    int selectIfExistByUsername(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authentication_info
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authentication_info
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int insert(UserAuthenticationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authentication_info
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int insertSelective(UserAuthenticationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authentication_info
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    UserAuthenticationInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authentication_info
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int updateByPrimaryKeySelective(UserAuthenticationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authentication_info
     *
     * @mbg.generated 2019-05-05 11:28:05
     */
    int updateByPrimaryKey(UserAuthenticationInfo record);
}